[app]
production = false
bind_addr = ["127.0.0.1", 9999]
db_addr = "postgres://postgres:123456@localhost/rbph"
kv_addr = "redis://localhost/1"
secret_key = "cmJwaDIwMjZAZGV2"

[auth]
max_session = 3

[auth.captcha]

[auth.email]
enabled = false
sender = "RBPH <bot@rabbi.town>"
smtp = ""
smtp_user = ""
smtp_pass = ""

[auth.email.url]
verify = "http://localhost/verify?token={}"
